### ISSUE TITLE
webview ver. 2.1.2 compilation issue for iOS - 'Unity-iPhone' is deprecated

### ISSUE THREAD

**Issue by JanFromNaomiAnimation** [readyplayerme/rpm-unity-sdk-webview#31]
**Describe the bug**
after update from 2.0.0 to 2.1.2 there is compilation exception for iOS platform, as calling: Calling TargetGuidByName with name='Unity-iPhone' is deprecated:

Exception: Calling TargetGuidByName with name='Unity-iPhone' is deprecated. There are two targets now, call GetUnityMainTargetGuid() - for app or GetUnityFrameworkTargetGuid() - for source/plugins to get Guid instead.
UnityEditor.iOS.Xcode.PBXProject.TargetGuidByName (System.String name) (at <a6ad200ae82e4c9aadecc9e564d7ebf5>:0)
ReadyPlayerMe.WebView.Editor.IOSBuildProcessor.OnPostprocessBuild (UnityEditor.BuildTarget target, System.String pathToBuiltProject) (at ./Library/PackageCache/com.readyplayerme.webview@0bfdb57191/Editor/IOSBuildProcessor.cs:18)
System.Reflection.RuntimeMethodInfo.Invoke (System.Object obj, System.Reflection.BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at <b1c407d3d1e249159ce5db32e3891ab6>:0)
UnityEngine.GUIUtility:ProcessEvent(Int32, IntPtr, Boolean&) (at /Users/bokken/build/output/unity/unity/Modules/IMGUI/GUIUtility.cs:206)

**To Reproduce**
1. update to 2.1.2
2. build project for iOS
3. See exception

**Expected behavior**
no compilation errors

**Desktop (please complete the following information):**
 - Ready Player Me Core version 4.1.2
 - Ready Player Me WebView version 2.1.2
 - glTFast version 5.0.4
 - Unity Editor version 2023.2.4f1 (but same will be also on older versions: https://forum.unity.com/threads/2019-3-0b3-0b4-calling-targetguidbynamewithname-unity-iphone-is-deprecated-wont-build.749003/)
 - Render Pipeline and version URP 16.0
 - Operating System Mac
 - Platform: iOS
 
thnx a lot for fix

**Comment by HarrisonHough** [comment]
Thanks for letting us know!
We just released a hotfix for this. 
Let us know if you are still having issues.

**Comment by JanFromNaomiAnimation** [comment]
Still compilation issues in 2.1.3
Compilation issue on Unity side is gone, but there is compilation problem in xcode (15.2)
![Screenshot 2024-01-19 at 13 48 17](https://github.com/readyplayerme/rpm-unity-sdk-webview/assets/124244732/257f3c48-ca48-465f-817d-090c48b795d9)
