### ISSUE TITLE
Compilation errors in xcode after update from 2.0.0 to 2.1.3

### ISSUE THREAD

**Issue by JanFromNaomiAnimation** [readyplayerme/rpm-unity-sdk-webview#36]
**Describe the bug**
Compilation errors in xcode after webview update from 2.0.0 to 2.1.3

**To Reproduce**
1. update webview package in any existing project with RPM from version 2.0.0 to 2.1.3
2. build for iOS platform
3. xcode project successfully created
4. try to run on device
5. compilation errors:

**Expected behavior**
no compilation errors

**Screenshots**
![image](https://github.com/readyplayerme/rpm-unity-sdk-webview/assets/124244732/254aaf08-fe75-4bde-b9d3-aacf85d14826)

 - Ready Player Me Core version 6.0.0
 - Ready Player Me WebView version 2.1.3
 - glTFast version 6.0.1
 - Unity Editor version 2023.4.2f1
 - Render Pipeline and version URP 16
 - Operating System Mac
 - Platform: iOS

**Comment by HarrisonHough** [comment]
This will be fixed in the next release 
https://github.com/readyplayerme/rpm-unity-sdk-webview/pull/37

**Comment by HarrisonHough** [comment]
This should be fixed in the latest release 
https://github.com/readyplayerme/rpm-unity-sdk-webview/releases/tag/v2.2.1
